const callsignPrefixes: Record<string, { country: string; flag: string }> = {
  'A2': { country: 'Botswana', flag: '🇧🇼' },
  'A3': { country: 'Tonga', flag: '🇹🇴' },
  'A4': { country: 'Oman', flag: '🇴🇲' },
  'A5': { country: 'Bhutan', flag: '🇧🇹' },
  'A6': { country: 'UAE', flag: '🇦🇪' },
  'A7': { country: 'Qatar', flag: '🇶🇦' },
  'A9': { country: 'Bahrain', flag: '🇧🇭' },
  'AP': { country: 'Pakistan', flag: '🇵🇰' },
  'B': { country: 'China', flag: '🇨🇳' },
  'BV': { country: 'Taiwan', flag: '🇹🇼' },
  'C3': { country: 'Andorra', flag: '🇦🇩' },
  'C5': { country: 'Gambia', flag: '🇬🇲' },
  'C6': { country: 'Bahamas', flag: '🇧🇸' },
  'CE': { country: 'Chile', flag: '🇨🇱' },
  'CM': { country: 'Cuba', flag: '🇨🇺' },
  'CO': { country: 'Cuba', flag: '🇨🇺' },
  'CP': { country: 'Bolivia', flag: '🇧🇴' },
  'CT': { country: 'Portugal', flag: '🇵🇹' },
  'CU': { country: 'Portugal', flag: '🇵🇹' },
  'CX': { country: 'Uruguay', flag: '🇺🇾' },
  'D2': { country: 'Angola', flag: '🇦🇴' },
  'D4': { country: 'Cape Verde', flag: '🇨🇻' },
  'DL': { country: 'Germany', flag: '🇩🇪' },
  'DA': { country: 'Germany', flag: '🇩🇪' },
  'DB': { country: 'Germany', flag: '🇩🇪' },
  'DC': { country: 'Germany', flag: '🇩🇪' },
  'DD': { country: 'Germany', flag: '🇩🇪' },
  'DE': { country: 'Germany', flag: '🇩🇪' },
  'DF': { country: 'Germany', flag: '🇩🇪' },
  'DG': { country: 'Germany', flag: '🇩🇪' },
  'DH': { country: 'Germany', flag: '🇩🇪' },
  'DI': { country: 'Germany', flag: '🇩🇪' },
  'DJ': { country: 'Germany', flag: '🇩🇪' },
  'DK': { country: 'Germany', flag: '🇩🇪' },
  'DM': { country: 'Germany', flag: '🇩🇪' },
  'DN': { country: 'Germany', flag: '🇩🇪' },
  'DO': { country: 'Germany', flag: '🇩🇪' },
  'DP': { country: 'Germany', flag: '🇩🇪' },
  'DQ': { country: 'Germany', flag: '🇩🇪' },
  'DR': { country: 'Germany', flag: '🇩🇪' },
  'DU': { country: 'Philippines', flag: '🇵🇭' },
  'E2': { country: 'Thailand', flag: '🇹🇭' },
  'E3': { country: 'Eritrea', flag: '🇪🇷' },
  'E4': { country: 'Palestine', flag: '🇵🇸' },
  'E5': { country: 'Cook Islands', flag: '🇨🇰' },
  'E6': { country: 'Niue', flag: '🇳🇺' },
  'E7': { country: 'Bosnia', flag: '🇧🇦' },
  'EA': { country: 'Spain', flag: '🇪🇸' },
  'EB': { country: 'Spain', flag: '🇪🇸' },
  'EC': { country: 'Spain', flag: '🇪🇸' },
  'ED': { country: 'Spain', flag: '🇪🇸' },
  'EE': { country: 'Spain', flag: '🇪🇸' },
  'EF': { country: 'Spain', flag: '🇪🇸' },
  'EG': { country: 'Spain', flag: '🇪🇸' },
  'EH': { country: 'Spain', flag: '🇪🇸' },
  'EI': { country: 'Ireland', flag: '🇮🇪' },
  'EJ': { country: 'Ireland', flag: '🇮🇪' },
  'EK': { country: 'Armenia', flag: '🇦🇲' },
  'EL': { country: 'Liberia', flag: '🇱🇷' },
  'EP': { country: 'Iran', flag: '🇮🇷' },
  'EQ': { country: 'Iran', flag: '🇮🇷' },
  'ER': { country: 'Moldova', flag: '🇲🇩' },
  'ES': { country: 'Estonia', flag: '🇪🇪' },
  'ET': { country: 'Ethiopia', flag: '🇪🇹' },
  'EU': { country: 'Belarus', flag: '🇧🇾' },
  'EV': { country: 'Belarus', flag: '🇧🇾' },
  'EW': { country: 'Belarus', flag: '🇧🇾' },
  'EX': { country: 'Kyrgyzstan', flag: '🇰🇬' },
  'EY': { country: 'Tajikistan', flag: '🇹🇯' },
  'EZ': { country: 'Turkmenistan', flag: '🇹🇲' },
  'F': { country: 'France', flag: '🇫🇷' },
  'G': { country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  'GD': { country: 'Isle of Man', flag: '🇮🇲' },
  'GI': { country: 'N. Ireland', flag: '🇬🇧' },
  'GJ': { country: 'Jersey', flag: '🇯🇪' },
  'GM': { country: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  'GU': { country: 'Guernsey', flag: '🇬🇬' },
  'GW': { country: 'Wales', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  'H4': { country: 'Solomon Is.', flag: '🇸🇧' },
  'HA': { country: 'Hungary', flag: '🇭🇺' },
  'HB': { country: 'Switzerland', flag: '🇨🇭' },
  'HB0': { country: 'Liechtenstein', flag: '🇱🇮' },
  'HC': { country: 'Ecuador', flag: '🇪🇨' },
  'HH': { country: 'Haiti', flag: '🇭🇹' },
  'HI': { country: 'Dominican Rep.', flag: '🇩🇴' },
  'HK': { country: 'Colombia', flag: '🇨🇴' },
  'HL': { country: 'South Korea', flag: '🇰🇷' },
  'HP': { country: 'Panama', flag: '🇵🇦' },
  'HR': { country: 'Honduras', flag: '🇭🇳' },
  'HS': { country: 'Thailand', flag: '🇹🇭' },
  'HV': { country: 'Vatican', flag: '🇻🇦' },
  'HZ': { country: 'Saudi Arabia', flag: '🇸🇦' },
  'I': { country: 'Italy', flag: '🇮🇹' },
  'IK': { country: 'Italy', flag: '🇮🇹' },
  'IN': { country: 'Italy', flag: '🇮🇹' },
  'IS': { country: 'Italy', flag: '🇮🇹' },
  'IT': { country: 'Italy', flag: '🇮🇹' },
  'IU': { country: 'Italy', flag: '🇮🇹' },
  'IV': { country: 'Italy', flag: '🇮🇹' },
  'IW': { country: 'Italy', flag: '🇮🇹' },
  'IZ': { country: 'Italy', flag: '🇮🇹' },
  'J2': { country: 'Djibouti', flag: '🇩🇯' },
  'J3': { country: 'Grenada', flag: '🇬🇩' },
  'J5': { country: 'Guinea-Bissau', flag: '🇬🇼' },
  'J6': { country: 'St. Lucia', flag: '🇱🇨' },
  'J7': { country: 'Dominica', flag: '🇩🇲' },
  'J8': { country: 'St. Vincent', flag: '🇻🇨' },
  'JA': { country: 'Japan', flag: '🇯🇵' },
  'JD': { country: 'Japan', flag: '🇯🇵' },
  'JE': { country: 'Japan', flag: '🇯🇵' },
  'JF': { country: 'Japan', flag: '🇯🇵' },
  'JG': { country: 'Japan', flag: '🇯🇵' },
  'JH': { country: 'Japan', flag: '🇯🇵' },
  'JI': { country: 'Japan', flag: '🇯🇵' },
  'JJ': { country: 'Japan', flag: '🇯🇵' },
  'JK': { country: 'Japan', flag: '🇯🇵' },
  'JL': { country: 'Japan', flag: '🇯🇵' },
  'JM': { country: 'Japan', flag: '🇯🇵' },
  'JN': { country: 'Japan', flag: '🇯🇵' },
  'JO': { country: 'Japan', flag: '🇯🇵' },
  'JP': { country: 'Japan', flag: '🇯🇵' },
  'JQ': { country: 'Japan', flag: '🇯🇵' },
  'JR': { country: 'Japan', flag: '🇯🇵' },
  'JS': { country: 'Japan', flag: '🇯🇵' },
  'JT': { country: 'Mongolia', flag: '🇲🇳' },
  'JU': { country: 'Mongolia', flag: '🇲🇳' },
  'JV': { country: 'Mongolia', flag: '🇲🇳' },
  'JW': { country: 'Svalbard', flag: '🇳🇴' },
  'JX': { country: 'Jan Mayen', flag: '🇳🇴' },
  'JY': { country: 'Jordan', flag: '🇯🇴' },
  'K': { country: 'USA', flag: '🇺🇸' },
  'KA': { country: 'USA', flag: '🇺🇸' },
  'KB': { country: 'USA', flag: '🇺🇸' },
  'KC': { country: 'USA', flag: '🇺🇸' },
  'KD': { country: 'USA', flag: '🇺🇸' },
  'KE': { country: 'USA', flag: '🇺🇸' },
  'KF': { country: 'USA', flag: '🇺🇸' },
  'KG': { country: 'USA', flag: '🇺🇸' },
  'KH': { country: 'USA', flag: '🇺🇸' },
  'KI': { country: 'USA', flag: '🇺🇸' },
  'KJ': { country: 'USA', flag: '🇺🇸' },
  'KK': { country: 'USA', flag: '🇺🇸' },
  'KL': { country: 'USA', flag: '🇺🇸' },
  'KM': { country: 'USA', flag: '🇺🇸' },
  'KN': { country: 'USA', flag: '🇺🇸' },
  'KO': { country: 'USA', flag: '🇺🇸' },
  'KP': { country: 'USA', flag: '🇺🇸' },
  'KQ': { country: 'USA', flag: '🇺🇸' },
  'KR': { country: 'USA', flag: '🇺🇸' },
  'KS': { country: 'USA', flag: '🇺🇸' },
  'KT': { country: 'USA', flag: '🇺🇸' },
  'KU': { country: 'USA', flag: '🇺🇸' },
  'KV': { country: 'USA', flag: '🇺🇸' },
  'KW': { country: 'USA', flag: '🇺🇸' },
  'KX': { country: 'USA', flag: '🇺🇸' },
  'KY': { country: 'USA', flag: '🇺🇸' },
  'KZ': { country: 'USA', flag: '🇺🇸' },
  'LA': { country: 'Norway', flag: '🇳🇴' },
  'LB': { country: 'Norway', flag: '🇳🇴' },
  'LC': { country: 'Norway', flag: '🇳🇴' },
  'LD': { country: 'Norway', flag: '🇳🇴' },
  'LE': { country: 'Norway', flag: '🇳🇴' },
  'LF': { country: 'Norway', flag: '🇳🇴' },
  'LG': { country: 'Norway', flag: '🇳🇴' },
  'LH': { country: 'Norway', flag: '🇳🇴' },
  'LI': { country: 'Norway', flag: '🇳🇴' },
  'LJ': { country: 'Norway', flag: '🇳🇴' },
  'LK': { country: 'Norway', flag: '🇳🇴' },
  'LL': { country: 'Norway', flag: '🇳🇴' },
  'LM': { country: 'Norway', flag: '🇳🇴' },
  'LN': { country: 'Norway', flag: '🇳🇴' },
  'LO': { country: 'Argentina', flag: '🇦🇷' },
  'LP': { country: 'Argentina', flag: '🇦🇷' },
  'LQ': { country: 'Argentina', flag: '🇦🇷' },
  'LR': { country: 'Argentina', flag: '🇦🇷' },
  'LS': { country: 'Argentina', flag: '🇦🇷' },
  'LT': { country: 'Argentina', flag: '🇦🇷' },
  'LU': { country: 'Argentina', flag: '🇦🇷' },
  'LV': { country: 'Argentina', flag: '🇦🇷' },
  'LW': { country: 'Argentina', flag: '🇦🇷' },
  'LX': { country: 'Luxembourg', flag: '🇱🇺' },
  'LY': { country: 'Lithuania', flag: '🇱🇹' },
  'LZ': { country: 'Bulgaria', flag: '🇧🇬' },
  'N': { country: 'USA', flag: '🇺🇸' },
  'OA': { country: 'Peru', flag: '🇵🇪' },
  'OB': { country: 'Peru', flag: '🇵🇪' },
  'OC': { country: 'Peru', flag: '🇵🇪' },
  'OD': { country: 'Lebanon', flag: '🇱🇧' },
  'OE': { country: 'Austria', flag: '🇦🇹' },
  'OF': { country: 'Finland', flag: '🇫🇮' },
  'OG': { country: 'Finland', flag: '🇫🇮' },
  'OH': { country: 'Finland', flag: '🇫🇮' },
  'OI': { country: 'Finland', flag: '🇫🇮' },
  'OJ': { country: 'Finland', flag: '🇫🇮' },
  'OK': { country: 'Czechia', flag: '🇨🇿' },
  'OL': { country: 'Czechia', flag: '🇨🇿' },
  'OM': { country: 'Slovakia', flag: '🇸🇰' },
  'ON': { country: 'Belgium', flag: '🇧🇪' },
  'OO': { country: 'Belgium', flag: '🇧🇪' },
  'OP': { country: 'Belgium', flag: '🇧🇪' },
  'OQ': { country: 'Belgium', flag: '🇧🇪' },
  'OR': { country: 'Belgium', flag: '🇧🇪' },
  'OS': { country: 'Belgium', flag: '🇧🇪' },
  'OT': { country: 'Belgium', flag: '🇧🇪' },
  'OU': { country: 'Denmark', flag: '🇩🇰' },
  'OV': { country: 'Denmark', flag: '🇩🇰' },
  'OW': { country: 'Denmark', flag: '🇩🇰' },
  'OX': { country: 'Greenland', flag: '🇬🇱' },
  'OY': { country: 'Faroe Is.', flag: '🇫🇴' },
  'OZ': { country: 'Denmark', flag: '🇩🇰' },
  'P2': { country: 'Papua NG', flag: '🇵🇬' },
  'P4': { country: 'Aruba', flag: '🇦🇼' },
  'P5': { country: 'North Korea', flag: '🇰🇵' },
  'PA': { country: 'Netherlands', flag: '🇳🇱' },
  'PB': { country: 'Netherlands', flag: '🇳🇱' },
  'PC': { country: 'Netherlands', flag: '🇳🇱' },
  'PD': { country: 'Netherlands', flag: '🇳🇱' },
  'PE': { country: 'Netherlands', flag: '🇳🇱' },
  'PF': { country: 'Netherlands', flag: '🇳🇱' },
  'PG': { country: 'Netherlands', flag: '🇳🇱' },
  'PH': { country: 'Netherlands', flag: '🇳🇱' },
  'PI': { country: 'Netherlands', flag: '🇳🇱' },
  'PJ': { country: 'Netherlands', flag: '🇳🇱' },
  'PP': { country: 'Brazil', flag: '🇧🇷' },
  'PQ': { country: 'Brazil', flag: '🇧🇷' },
  'PR': { country: 'Brazil', flag: '🇧🇷' },
  'PS': { country: 'Brazil', flag: '🇧🇷' },
  'PT': { country: 'Brazil', flag: '🇧🇷' },
  'PU': { country: 'Brazil', flag: '🇧🇷' },
  'PV': { country: 'Brazil', flag: '🇧🇷' },
  'PW': { country: 'Brazil', flag: '🇧🇷' },
  'PX': { country: 'Brazil', flag: '🇧🇷' },
  'PY': { country: 'Brazil', flag: '🇧🇷' },
  'PZ': { country: 'Suriname', flag: '🇸🇷' },
  'R': { country: 'Russia', flag: '🇷🇺' },
  'RA': { country: 'Russia', flag: '🇷🇺' },
  'S2': { country: 'Bangladesh', flag: '🇧🇩' },
  'S5': { country: 'Slovenia', flag: '🇸🇮' },
  'S7': { country: 'Seychelles', flag: '🇸🇨' },
  'S9': { country: 'Sao Tome', flag: '🇸🇹' },
  'SA': { country: 'Sweden', flag: '🇸🇪' },
  'SB': { country: 'Sweden', flag: '🇸🇪' },
  'SC': { country: 'Sweden', flag: '🇸🇪' },
  'SD': { country: 'Sweden', flag: '🇸🇪' },
  'SE': { country: 'Sweden', flag: '🇸🇪' },
  'SF': { country: 'Sweden', flag: '🇸🇪' },
  'SG': { country: 'Sweden', flag: '🇸🇪' },
  'SH': { country: 'Sweden', flag: '🇸🇪' },
  'SI': { country: 'Sweden', flag: '🇸🇪' },
  'SJ': { country: 'Sweden', flag: '🇸🇪' },
  'SK': { country: 'Sweden', flag: '🇸🇪' },
  'SL': { country: 'Sweden', flag: '🇸🇪' },
  'SM': { country: 'Sweden', flag: '🇸🇪' },
  'SN': { country: 'Poland', flag: '🇵🇱' },
  'SO': { country: 'Poland', flag: '🇵🇱' },
  'SP': { country: 'Poland', flag: '🇵🇱' },
  'SQ': { country: 'Poland', flag: '🇵🇱' },
  'SR': { country: 'Poland', flag: '🇵🇱' },
  'ST': { country: 'Sudan', flag: '🇸🇩' },
  'SU': { country: 'Egypt', flag: '🇪🇬' },
  'SV': { country: 'Greece', flag: '🇬🇷' },
  'SW': { country: 'Greece', flag: '🇬🇷' },
  'SX': { country: 'Greece', flag: '🇬🇷' },
  'SY': { country: 'Greece', flag: '🇬🇷' },
  'SZ': { country: 'Greece', flag: '🇬🇷' },
  'T2': { country: 'Tuvalu', flag: '🇹🇻' },
  'T5': { country: 'Somalia', flag: '🇸🇴' },
  'T7': { country: 'San Marino', flag: '🇸🇲' },
  'T8': { country: 'Palau', flag: '🇵🇼' },
  'T9': { country: 'Bosnia', flag: '🇧🇦' },
  'TA': { country: 'Turkey', flag: '🇹🇷' },
  'TB': { country: 'Turkey', flag: '🇹🇷' },
  'TC': { country: 'Turkey', flag: '🇹🇷' },
  'TF': { country: 'Iceland', flag: '🇮🇸' },
  'TG': { country: 'Guatemala', flag: '🇬🇹' },
  'TI': { country: 'Costa Rica', flag: '🇨🇷' },
  'TJ': { country: 'Cameroon', flag: '🇨🇲' },
  'TK': { country: 'Corsica', flag: '🇫🇷' },
  'TL': { country: 'CAR', flag: '🇨🇫' },
  'TN': { country: 'Congo', flag: '🇨🇬' },
  'TR': { country: 'Gabon', flag: '🇬🇦' },
  'TT': { country: 'Chad', flag: '🇹🇩' },
  'TU': { country: 'Ivory Coast', flag: '🇨🇮' },
  'TY': { country: 'Benin', flag: '🇧🇯' },
  'TZ': { country: 'Mali', flag: '🇲🇱' },
  'UA': { country: 'Russia', flag: '🇷🇺' },
  'UB': { country: 'Russia', flag: '🇷🇺' },
  'UC': { country: 'Russia', flag: '🇷🇺' },
  'UD': { country: 'Russia', flag: '🇷🇺' },
  'UE': { country: 'Russia', flag: '🇷🇺' },
  'UF': { country: 'Russia', flag: '🇷🇺' },
  'UG': { country: 'Russia', flag: '🇷🇺' },
  'UH': { country: 'Russia', flag: '🇷🇺' },
  'UI': { country: 'Russia', flag: '🇷🇺' },
  'UK': { country: 'Uzbekistan', flag: '🇺🇿' },
  'UN': { country: 'Kazakhstan', flag: '🇰🇿' },
  'UR': { country: 'Ukraine', flag: '🇺🇦' },
  'US': { country: 'Ukraine', flag: '🇺🇦' },
  'UT': { country: 'Ukraine', flag: '🇺🇦' },
  'UU': { country: 'Ukraine', flag: '🇺🇦' },
  'UV': { country: 'Ukraine', flag: '🇺🇦' },
  'UW': { country: 'Ukraine', flag: '🇺🇦' },
  'UX': { country: 'Ukraine', flag: '🇺🇦' },
  'UY': { country: 'Ukraine', flag: '🇺🇦' },
  'UZ': { country: 'Ukraine', flag: '🇺🇦' },
  'V2': { country: 'Antigua', flag: '🇦🇬' },
  'V3': { country: 'Belize', flag: '🇧🇿' },
  'V4': { country: 'St. Kitts', flag: '🇰🇳' },
  'V5': { country: 'Namibia', flag: '🇳🇦' },
  'V6': { country: 'Micronesia', flag: '🇫🇲' },
  'V7': { country: 'Marshall Is.', flag: '🇲🇭' },
  'V8': { country: 'Brunei', flag: '🇧🇳' },
  'VA': { country: 'Canada', flag: '🇨🇦' },
  'VB': { country: 'Canada', flag: '🇨🇦' },
  'VC': { country: 'Canada', flag: '🇨🇦' },
  'VD': { country: 'Canada', flag: '🇨🇦' },
  'VE': { country: 'Canada', flag: '🇨🇦' },
  'VF': { country: 'Canada', flag: '🇨🇦' },
  'VG': { country: 'Canada', flag: '🇨🇦' },
  'VK': { country: 'Australia', flag: '🇦🇺' },
  'VL': { country: 'Australia', flag: '🇦🇺' },
  'VM': { country: 'Australia', flag: '🇦🇺' },
  'VN': { country: 'Australia', flag: '🇦🇺' },
  'VO': { country: 'Canada', flag: '🇨🇦' },
  'VP': { country: 'UK Overseas', flag: '🇬🇧' },
  'VQ': { country: 'UK Overseas', flag: '🇬🇧' },
  'VR': { country: 'Hong Kong', flag: '🇭🇰' },
  'VS': { country: 'UK Overseas', flag: '🇬🇧' },
  'VU': { country: 'India', flag: '🇮🇳' },
  'VX': { country: 'Canada', flag: '🇨🇦' },
  'VY': { country: 'Canada', flag: '🇨🇦' },
  'W': { country: 'USA', flag: '🇺🇸' },
  'XA': { country: 'Mexico', flag: '🇲🇽' },
  'XB': { country: 'Mexico', flag: '🇲🇽' },
  'XC': { country: 'Mexico', flag: '🇲🇽' },
  'XD': { country: 'Mexico', flag: '🇲🇽' },
  'XE': { country: 'Mexico', flag: '🇲🇽' },
  'XF': { country: 'Mexico', flag: '🇲🇽' },
  'XG': { country: 'Mexico', flag: '🇲🇽' },
  'XH': { country: 'Mexico', flag: '🇲🇽' },
  'XI': { country: 'Mexico', flag: '🇲🇽' },
  'XT': { country: 'Burkina Faso', flag: '🇧🇫' },
  'XU': { country: 'Cambodia', flag: '🇰🇭' },
  'XV': { country: 'Vietnam', flag: '🇻🇳' },
  'XW': { country: 'Laos', flag: '🇱🇦' },
  'XX': { country: 'Macau', flag: '🇲🇴' },
  'XY': { country: 'Myanmar', flag: '🇲🇲' },
  'XZ': { country: 'Myanmar', flag: '🇲🇲' },
  'YA': { country: 'Afghanistan', flag: '🇦🇫' },
  'YB': { country: 'Indonesia', flag: '🇮🇩' },
  'YC': { country: 'Indonesia', flag: '🇮🇩' },
  'YD': { country: 'Indonesia', flag: '🇮🇩' },
  'YE': { country: 'Indonesia', flag: '🇮🇩' },
  'YF': { country: 'Indonesia', flag: '🇮🇩' },
  'YG': { country: 'Indonesia', flag: '🇮🇩' },
  'YH': { country: 'Indonesia', flag: '🇮🇩' },
  'YI': { country: 'Iraq', flag: '🇮🇶' },
  'YJ': { country: 'Vanuatu', flag: '🇻🇺' },
  'YK': { country: 'Syria', flag: '🇸🇾' },
  'YL': { country: 'Latvia', flag: '🇱🇻' },
  'YN': { country: 'Nicaragua', flag: '🇳🇮' },
  'YO': { country: 'Romania', flag: '🇷🇴' },
  'YP': { country: 'Romania', flag: '🇷🇴' },
  'YQ': { country: 'Romania', flag: '🇷🇴' },
  'YR': { country: 'Romania', flag: '🇷🇴' },
  'YS': { country: 'El Salvador', flag: '🇸🇻' },
  'YT': { country: 'Serbia', flag: '🇷🇸' },
  'YU': { country: 'Serbia', flag: '🇷🇸' },
  'YV': { country: 'Venezuela', flag: '🇻🇪' },
  'YW': { country: 'Venezuela', flag: '🇻🇪' },
  'YX': { country: 'Venezuela', flag: '🇻🇪' },
  'YY': { country: 'Venezuela', flag: '🇻🇪' },
  'Z2': { country: 'Zimbabwe', flag: '🇿🇼' },
  'Z3': { country: 'N. Macedonia', flag: '🇲🇰' },
  'Z8': { country: 'South Sudan', flag: '🇸🇸' },
  'ZA': { country: 'Albania', flag: '🇦🇱' },
  'ZB': { country: 'Gibraltar', flag: '🇬🇮' },
  'ZC': { country: 'UK Overseas', flag: '🇬🇧' },
  'ZD': { country: 'UK Overseas', flag: '🇬🇧' },
  'ZF': { country: 'Cayman Is.', flag: '🇰🇾' },
  'ZK': { country: 'New Zealand', flag: '🇳🇿' },
  'ZL': { country: 'New Zealand', flag: '🇳🇿' },
  'ZM': { country: 'New Zealand', flag: '🇳🇿' },
  'ZP': { country: 'Paraguay', flag: '🇵🇾' },
  'ZR': { country: 'South Africa', flag: '🇿🇦' },
  'ZS': { country: 'South Africa', flag: '🇿🇦' },
  'ZT': { country: 'South Africa', flag: '🇿🇦' },
  'ZU': { country: 'South Africa', flag: '🇿🇦' },
  'ZV': { country: 'Brazil', flag: '🇧🇷' },
  'ZW': { country: 'Brazil', flag: '🇧🇷' },
  'ZX': { country: 'Brazil', flag: '🇧🇷' },
  'ZY': { country: 'Brazil', flag: '🇧🇷' },
  'ZZ': { country: 'Brazil', flag: '🇧🇷' },
  '3A': { country: 'Monaco', flag: '🇲🇨' },
  '3B': { country: 'Mauritius', flag: '🇲🇺' },
  '3C': { country: 'Eq. Guinea', flag: '🇬🇶' },
  '3D': { country: 'eSwatini', flag: '🇸🇿' },
  '3V': { country: 'Tunisia', flag: '🇹🇳' },
  '3W': { country: 'Vietnam', flag: '🇻🇳' },
  '3X': { country: 'Guinea', flag: '🇬🇳' },
  '3Y': { country: 'Norway', flag: '🇳🇴' },
  '3Z': { country: 'Poland', flag: '🇵🇱' },
  '4J': { country: 'Azerbaijan', flag: '🇦🇿' },
  '4K': { country: 'Azerbaijan', flag: '🇦🇿' },
  '4L': { country: 'Georgia', flag: '🇬🇪' },
  '4O': { country: 'Montenegro', flag: '🇲🇪' },
  '4S': { country: 'Sri Lanka', flag: '🇱🇰' },
  '4U': { country: 'UN', flag: '🇺🇳' },
  '4W': { country: 'Timor-Leste', flag: '🇹🇱' },
  '4X': { country: 'Israel', flag: '🇮🇱' },
  '4Z': { country: 'Israel', flag: '🇮🇱' },
  '5A': { country: 'Libya', flag: '🇱🇾' },
  '5B': { country: 'Cyprus', flag: '🇨🇾' },
  '5H': { country: 'Tanzania', flag: '🇹🇿' },
  '5I': { country: 'Tanzania', flag: '🇹🇿' },
  '5N': { country: 'Nigeria', flag: '🇳🇬' },
  '5O': { country: 'Nigeria', flag: '🇳🇬' },
  '5R': { country: 'Madagascar', flag: '🇲🇬' },
  '5S': { country: 'Madagascar', flag: '🇲🇬' },
  '5T': { country: 'Mauritania', flag: '🇲🇷' },
  '5U': { country: 'Niger', flag: '🇳🇪' },
  '5V': { country: 'Togo', flag: '🇹🇬' },
  '5W': { country: 'Samoa', flag: '🇼🇸' },
  '5X': { country: 'Uganda', flag: '🇺🇬' },
  '5Y': { country: 'Kenya', flag: '🇰🇪' },
  '5Z': { country: 'Kenya', flag: '🇰🇪' },
  '6V': { country: 'Senegal', flag: '🇸🇳' },
  '6W': { country: 'Senegal', flag: '🇸🇳' },
  '6Y': { country: 'Jamaica', flag: '🇯🇲' },
  '7O': { country: 'Yemen', flag: '🇾🇪' },
  '7P': { country: 'Lesotho', flag: '🇱🇸' },
  '7Q': { country: 'Malawi', flag: '🇲🇼' },
  '7T': { country: 'Algeria', flag: '🇩🇿' },
  '7U': { country: 'Algeria', flag: '🇩🇿' },
  '7V': { country: 'Algeria', flag: '🇩🇿' },
  '7W': { country: 'Algeria', flag: '🇩🇿' },
  '7X': { country: 'Algeria', flag: '🇩🇿' },
  '7Y': { country: 'Algeria', flag: '🇩🇿' },
  '7Z': { country: 'Saudi Arabia', flag: '🇸🇦' },
  '8P': { country: 'Barbados', flag: '🇧🇧' },
  '8Q': { country: 'Maldives', flag: '🇲🇻' },
  '8R': { country: 'Guyana', flag: '🇬🇾' },
  '9A': { country: 'Croatia', flag: '🇭🇷' },
  '9G': { country: 'Ghana', flag: '🇬🇭' },
  '9H': { country: 'Malta', flag: '🇲🇹' },
  '9I': { country: 'Zambia', flag: '🇿🇲' },
  '9J': { country: 'Zambia', flag: '🇿🇲' },
  '9K': { country: 'Kuwait', flag: '🇰🇼' },
  '9L': { country: 'Sierra Leone', flag: '🇸🇱' },
  '9M': { country: 'Malaysia', flag: '🇲🇾' },
  '9N': { country: 'Nepal', flag: '🇳🇵' },
  '9Q': { country: 'DRC', flag: '🇨🇩' },
  '9R': { country: 'DRC', flag: '🇨🇩' },
  '9S': { country: 'DRC', flag: '🇨🇩' },
  '9T': { country: 'DRC', flag: '🇨🇩' },
  '9U': { country: 'Burundi', flag: '🇧🇮' },
  '9V': { country: 'Singapore', flag: '🇸🇬' },
  '9W': { country: 'Malaysia', flag: '🇲🇾' },
  '9X': { country: 'Rwanda', flag: '🇷🇼' },
  '9Y': { country: 'Trinidad', flag: '🇹🇹' },
  '9Z': { country: 'Trinidad', flag: '🇹🇹' },
};

export function getCountryFromCallsign(callsign: string): { country: string; flag: string } | null {
  if (!callsign) return null;
  
  const upperCall = callsign.toUpperCase().trim();
  
  for (let len = 3; len >= 1; len--) {
    const prefix = upperCall.substring(0, len);
    if (callsignPrefixes[prefix]) {
      return callsignPrefixes[prefix];
    }
  }
  
  return null;
}

export function getFlagEmoji(callsign: string): string {
  const info = getCountryFromCallsign(callsign);
  return info?.flag || '🌐';
}

export function getCountryName(callsign: string): string {
  const info = getCountryFromCallsign(callsign);
  return info?.country || 'Unknown';
}
